[Security Solution][Endpoint] Update script library Delete API to not fail when SIEM rules check fails (#260765)
## Summary

- Changes the behaviour of the `ScriptsLibrary#delete()` method to not
fail if unable to check rules for usage of script
- Not all users may have access to read Rules, so in order to ensure
that users can still manage (delete) scripts, the logic around the
checking to see if Rules are using the `runscript` response action with
the script that is being deleted was changed to only log that error but
allow user to continue and delete the script
- In this case, if a rule was still referencing the script that was
deleted, when that rule is executed the `runscript` response action will
be created with an error indicating that script is not found.
- Fixes the Scripts Library List API docs to hide it from output

<br>

_____________


Screen capture of an Alerts whose `runscript` rule action was still
configured with a script that no longer exists:

<img width="3728" height="2446" alt="image"
src="https://github.com/user-attachments/assets/641a46e4-caa8-46b2-aebb-809ef0be674f"
/>


<br><br>



<details><summary>Click to view error logged when unable to check
rules</summary>

```
[2026-04-01T11:36:53.108-04:00][ERROR][plugins.securitySolution.ScriptsLibraryClient] ScriptLibraryError: Error while attempting to find rules using script ID(s) ["7ca2bf68-9d31-4eb6-bb8c-e3bf23392e37"]: Unauthorized to find rules for any rule types
    at ScriptsLibraryClient.findRulesUsingScripts (scripts_library_client.ts:364:21)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at ScriptsLibraryClient.delete (scripts_library_client.ts:628:7)
    at delete_script.ts:45:7
    at CoreVersionedRoute.handle (core_versioned_route.ts:216:20)
    at Router.handle (router.ts:209:30)
    at exports.Manager.execute (/Users/ptavares/WORKSPACES/kibana/node_modules/@hapi/hapi/lib/toolkit.js:60:28)
    at Object.internals.handler (/Users/ptavares/WORKSPACES/kibana/node_modules/@hapi/hapi/lib/handler.js:46:20)
    at exports.execute (/Users/ptavares/WORKSPACES/kibana/node_modules/@hapi/hapi/lib/handler.js:31:20)
    at Request._lifecycle (/Users/ptavares/WORKSPACES/kibana/node_modules/@hapi/hapi/lib/request.js:370:32)
    at Request._execute (/Users/ptavares/WORKSPACES/kibana/node_modules/@hapi/hapi/lib/request.js:280:9)
----- original error -----
Error: Unauthorized to find rules for any rule types
    at AlertingAuthorization.getAuthorizationFilter (alerting_authorization.ts:348:20)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at findRules (find_rules.ts:67:26)
    at ScriptsLibraryClient.findRulesUsingScripts (scripts_library_client.ts:344:28)
    at ScriptsLibraryClient.delete (scripts_library_client.ts:628:7)
    at delete_script.ts:45:7
    at CoreVersionedRoute.handle (core_versioned_route.ts:216:20)
    at Router.handle (router.ts:209:30)
    at exports.Manager.execute (/Users/ptavares/WORKSPACES/kibana/node_modules/@hapi/hapi/lib/toolkit.js:60:28)
    at Object.internals.handler (/Users/ptavares/WORKSPACES/kibana/node_modules/@hapi/hapi/lib/handler.js:46:20)
    at exports.execute (/Users/ptavares/WORKSPACES/kibana/node_modules/@hapi/hapi/lib/handler.js:31:20)
    at Request._lifecycle (/Users/ptavares/WORKSPACES/kibana/node_modules/@hapi/hapi/lib/request.js:370:32)
    at Request._execute (/Users/ptavares/WORKSPACES/kibana/node_modules/@hapi/hapi/lib/request.js:280:9)
[2026-04-01T11:36:53.108-04:00][ERROR][plugins.securitySolution.ScriptsLibraryClient] Proceeding with deletion of script [7ca2bf68-9d31-4eb6-bb8c-e3bf23392e37] even though check for script usage in rules failed
```

</details>







### Checklist

- [x] [Unit or functional
tests](https://www.elastic.co/guide/en/kibana/master/development-tests.html)
were updated or added to match the most common scenarios

---------

Co-authored-by: kibanamachine <42973632+kibanamachine@users.noreply.github.com>