[Obs AI Assistant] Add `p-timeout` to stabilize serverless API tests (#225420)
**Problem**
This error is happening intermittently:

> Serverless Observability - Deployment-agnostic AI Assistant API
integration tests
  observability AI Assistant
    Knowledge base: POST /internal/observability_ai_assistant/kb/setup
      returns 200 when model is deployed:
>
> Error: Timeout of 360000ms exceeded. For async tests and hooks, ensure
"done()" is called; if returning a Promise, ensure it resolves.
(/root/.qaf/data/git/kibana/x-pack/test/api_integration/deployment_agnostic/apis/observability/ai_assistant/knowledge_base/knowledge_base_setup.spec.ts)

It occurs because the async `deployTinyElserAndSetupKb` does not resolve
in time:


https://github.com/elastic/kibana/blob/68d904549129cce48dfc4292658f883b6c7460f3/x-pack/test/api_integration/deployment_agnostic/apis/observability/ai_assistant/knowledge_base/knowledge_base_setup.spec.ts#L51

`deployTinyElserAndSetupKb` is responsible for importing tiny_elser and
waiting for it to be allocated and available.
I'm not saying we don't have a bug on our end but I wouldn't be
surprised if this is an infra issue since this only happens on
serverless and not on stateful.

**Solution**

This PR attempts to fix the issue by retrying importing the model if it
has not succeeded after 1 minute. If the model is already imported it
will return gracefully.



## Dependency check list

- Purpose: `p-timeout` can be used to wrap async operation and ensure
they don't run indefinitely. In our case an operation is causing the
tests to timeout after 6 min and we want to avoid this by aborting the
operation after 30 seconds.

- Justification: The package is tiny, dependency-free, has TypeScript
types, widely used, and is easy to use. We already use `p-retry` and
several other deps from the same maintainer (Sindre Sorhus) so we
already have put some amount of trust in this maintainer

- Alternatives explored: Hand-rolled `Promise.race` wrappers risk subtle
clear/cancel bugs; RxJS’s `timeout` only works on `Observable`s; and
writing an in-house Kibana helper would just duplicate maintenance
effort. We can avoid this by consuming a proven library.

- Existing dependencies: Afaict we have no alternatives already other
than RxJS’s `timeout`. I've seen this implemented in various helpers
across the code base I think this dep fills a genuine gap.