chore(dep): Bump backport from `10.0.0` to `10.0.1` (#223864)
Changelog: https://github.com/sorenlouv/backport/releases/tag/v10.0.1

Updating to 10.0.1 fixes an issue where the backport tool would throw an
exception if SAML is not authenticated for the github access token used
by backport:

```
⚠️  Ouch! An unhandled error occured 😿
TypeError: Cannot read properties of undefined (reading 'type')
    at /Users/trentm/el/kibana/node_modules/backport/dist/lib/github/v4/getInvalidAccessTokenMessage.js:20:27
    at Array.some (<anonymous>)
    at getInvalidAccessTokenMessage (/Users/trentm/el/kibana/node_modules/backport/dist/lib/github/v4/getInvalidAccessTokenMessage.js:18:55)
    at getOptionsFromGithub (/Users/trentm/el/kibana/node_modules/backport/dist/lib/github/v4/getOptionsFromGithub/getOptionsFromGithub.js:38:109)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getOptions (/Users/trentm/el/kibana/node_modules/backport/dist/options/options.js:66:31)
    at async backportRun (/Users/trentm/el/kibana/node_modules/backport/dist/backportRun.js:51:19)
    at async Object.backportRun (/Users/trentm/el/kibana/node_modules/backport/dist/entrypoint.api.js:33:17)
Please open an issue in https://github.com/sorenlouv/backport/issues or contact me directly on https://twitter.com/sorenlouv
For additional details see the logs: /Users/trentm/.backport/backport.info.log
```

---------

Co-authored-by: kibanamachine <42973632+kibanamachine@users.noreply.github.com>