[scout tests] fix flaky FieldName typing for MKI (#249754)
## Summary

While running tests on MKI we see flakiness related to typing Field
Name:

```
Error: expect(locator).toHaveValue(expected) failed

Locator:  locator('.euiSuperSelect').filter({ has: locator('[data-test-subj="streamsAppFieldFormTypeSelect"]').first() }).locator('input[type="hidden"]')
Expected: "ip"
Received: ""
Timeout:  10000ms

Call log:
  - Expect "toHaveValue" with timeout 10000ms
  - waiting for locator('.euiSuperSelect').filter({ has: locator('[data-test-subj="streamsAppFieldFormTypeSelect"]').first() }).locator('input[type="hidden"]')
    14 × locator resolved to <input value="" type="hidden"/>
       - unexpected value ""

    at x-pack/platform/plugins/shared/streams_app/test/scout/ui/tests/data_management/data_mapping/wired_streams_schema.spec.ts:111:80
```

<img width="1280" height="720" alt="image"
src="https://github.com/user-attachments/assets/ce6b7ffe-6a72-405f-a76d-4cc8da9c3d53"
/>

This PR uses typing with delay that is closer to end-user experience and
should be more stable (reasonably slower)