[Security Solution] [Analyzer] Use correct unmapped type for tiebreaker (#153480)
## Summary

Related issue: https://github.com/elastic/kibana/issues/153189

Fixes an issue where when using analyzer with an integration that did
not map event.id, the unmapped_type on this changed line was wrong, as
normally this field is a keyword. This would cause the analyzer events
api request to fail with
```
ResponseError: search_phase_execution_exception
        Caused by:
                illegal_argument_exception: Can't sort on field [__anonymous_]; the field has incompatible sort types: [STRING] and [LONG] across shards!
        Root causes:
                task_cancelled_exception: parent task was cancelled [Fatal failure during search: failed to merge result [Can't sort on field [__anonymous_]; the field has incompatible sort types: [STRING] and [LONG] across shards!]]
```
Before:

![image](https://user-images.githubusercontent.com/56408403/226994873-f8a23051-3d00-4974-b4a3-06b6fffa2b4e.png)
After:

![image](https://user-images.githubusercontent.com/56408403/226994908-284efbe7-3599-4aca-aef6-f0cb43f91ce8.png)


### Checklist

- [ ] [Unit or functional
tests](https://www.elastic.co/guide/en/kibana/master/development-tests.html)
were updated or added to match the most common scenarios