[Security Solution][Endpoint] Add `illegal_index_shard_state_exception` as a transient ES error to FTR method that installs endpoint package (#162804)
## Summary

- Adds `illegal_index_shard_state_exception` to the list of errors that
should allow the `installOrUpgradeEndpointFleetPackage()` to re-try if
encountered.


Fixes: #72874 
(☝️  again 😞 )

Last error reported in above reference issue was:

```


Error: runtime_exception
--
Caused by:
  illegal_index_shard_state_exception: CurrentState[RECOVERING] operations only allowed when shard state is one of [POST_RECOVERY, STARTED]
```

---------

Co-authored-by: kibanamachine <42973632+kibanamachine@users.noreply.github.com>