[kbn-test] improve error handling for saml auth (#182511)
## Summary

If cloud user has no access to the project, we get error message like
`Error: Failed to parse SAML response value`. This error does not
explain the issue and especially because request returns 200 OK (due to
redirects)

This PR disables redirects for API call that creates SAML response, so
if user has no access to the project response code is 303. To better
explain the issue extended message is logged:

```
Error: Failed to parse SAML response value.
 │ Most likely the <user_email> user has no access to the cloud deployment.
 │ Login to <cloud hostname> with the user from '.ftr/role_users.json' file and try to load
 | <project_kibana_url> in the same window.
```

The PR also adds test coverage for the SAML auth in Cloud, to make sure
we don't break stuff with new changes

---------

Co-authored-by: kibanamachine <42973632+kibanamachine@users.noreply.github.com>