[ResponseOps] Fixes failing test: Jest Integration Tests.x-pack/platform/plugins/shared/task_manager/server/integration_tests - unrecognized task types should be no workload aggregator errors when there are removed task types (#221854)
Resolves https://github.com/elastic/kibana/issues/208459

## Summary

Unskips flaky test that was failing with the error below. This PR
updates the test to wait until the task is finished running before
checking that the status is marked as `unrecognized`.
```
Error: expect(received).toBe(expected) // Object.is equality

Expected: "unrecognized"
Received: "idle"
    at toBe (/opt/buildkite-agent/
```