Add missing import for docker_uiam (#250435)
Adds an import to resolve `TypeError: URL.parse is not a function`
failures when performing relevance evaluations for Agent Builder:

```
TypeError: URL.parse is not a function
    at Object.<anonymous> (/Users/kderusso/git_tree/kibana/src/platform/packages/shared/kbn-es/src/utils/docker_uiam.ts:83:24)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module.newCompile2 (/Users/kderusso/git_tree/kibana/node_modules/playwright/lib/third_party/pirates.js:46:29)
    at Module._compile (/Users/kderusso/git_tree/kibana/node_modules/pirates/lib/index.js:129:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Object.newLoader (/Users/kderusso/git_tree/kibana/node_modules/pirates/lib/index.js:134:7)
    at Object.newLoader2 [as .ts] (/Users/kderusso/git_tree/kibana/node_modules/playwright/lib/third_party/pirates.js:52:22)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at Module.patchedRequire (/Users/kderusso/git_tree/kibana/node_modules/require-in-the-middle/index.js:256:27)
    at Module.Hook._require.Module.require (/Users/kderusso/git_tree/kibana/node_modules/require-in-the-middle/index.js:181:27)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/Users/kderusso/git_tree/kibana/src/platform/packages/shared/kbn-es/src/utils/docker.ts:39:1)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module.newCompile2 (/Users/kderusso/git_tree/kibana/node_modules/playwright/lib/third_party/pirates.js:46:29)
    at Module._compile (/Users/kderusso/git_tree/kibana/node_modules/pirates/lib/index.js:129:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Object.newLoader (/Users/kderusso/git_tree/kibana/node_modules/pirates/lib/index.js:134:7)
    at Object.newLoader2 [as .ts] (/Users/kderusso/git_tree/kibana/node_modules/playwright/lib/third_party/pirates.js:52:22)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at Module.patchedRequire (/Users/kderusso/git_tree/kibana/node_modules/require-in-the-middle/index.js:256:27)
    at Module.Hook._require.Module.require (/Users/kderusso/git_tree/kibana/node_modules/require-in-the-middle/index.js:181:27)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/Users/kderusso/git_tree/kibana/src/platform/packages/shared/kbn-es/src/utils/index.ts:20:1)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module.newCompile2 (/Users/kderusso/git_tree/kibana/node_modules/playwright/lib/third_party/pirates.js:46:29)
    at Module._compile (/Users/kderusso/git_tree/kibana/node_modules/pirates/lib/index.js:129:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Object.newLoader (/Users/kderusso/git_tree/kibana/node_modules/pirates/lib/index.js:134:7)
    at Object.newLoader2 [as .ts] (/Users/kderusso/git_tree/kibana/node_modules/playwright/lib/third_party/pirates.js:52:22)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at Module.patchedRequire (/Users/kderusso/git_tree/kibana/node_modules/require-in-the-middle/index.js:256:27)
    at Module.Hook._require.Module.require (/Users/kderusso/git_tree/kibana/node_modules/require-in-the-middle/index.js:181:27)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/Users/kderusso/git_tree/kibana/src/platform/packages/shared/kbn-es/src/install/install_archive.ts:22:1)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module.newCompile2 (/Users/kderusso/git_tree/kibana/node_modules/playwright/lib/third_party/pirates.js:46:29)
    at Module._compile (/Users/kderusso/git_tree/kibana/node_modules/pirates/lib/index.js:129:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Object.newLoader (/Users/kderusso/git_tree/kibana/node_modules/pirates/lib/index.js:134:7)
    at Object.newLoader2 [as .ts] (/Users/kderusso/git_tree/kibana/node_modules/playwright/lib/third_party/pirates.js:52:22)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at Module.patchedRequire (/Users/kderusso/git_tree/kibana/node_modules/require-in-the-middle/index.js:256:27)
    at Module.Hook._require.Module.require (/Users/kderusso/git_tree/kibana/node_modules/require-in-the-middle/index.js:181:27)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/Users/kderusso/git_tree/kibana/src/platform/packages/shared/kbn-es/src/install/index.ts:10:1)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module.newCompile2 (/Users/kderusso/git_tree/kibana/node_modules/playwright/lib/third_party/pirates.js:46:29)
    at Module._compile (/Users/kderusso/git_tree/kibana/node_modules/pirates/lib/index.js:129:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Object.newLoader (/Users/kderusso/git_tree/kibana/node_modules/pirates/lib/index.js:134:7)
    at Object.newLoader2 [as .ts] (/Users/kderusso/git_tree/kibana/node_modules/playwright/lib/third_party/pirates.js:52:22)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at Module.patchedRequire (/Users/kderusso/git_tree/kibana/node_modules/require-in-the-middle/index.js:256:27)
    at Module.Hook._require.Module.require (/Users/kderusso/git_tree/kibana/node_modules/require-in-the-middle/index.js:181:27)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/Users/kderusso/git_tree/kibana/src/platform/packages/shared/kbn-es/src/cluster.ts:23:1)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module.newCompile2 (/Users/kderusso/git_tree/kibana/node_modules/playwright/lib/third_party/pirates.js:46:29)
    at Module._compile (/Users/kderusso/git_tree/kibana/node_modules/pirates/lib/index.js:129:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Object.newLoader (/Users/kderusso/git_tree/kibana/node_modules/pirates/lib/index.js:134:7)
    at Object.newLoader2 [as .ts] (/Users/kderusso/git_tree/kibana/node_modules/playwright/lib/third_party/pirates.js:52:22)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at Module.patchedRequire (/Users/kderusso/git_tree/kibana/node_modules/require-in-the-middle/index.js:256:27)
    at Module.Hook._require.Module.require (/Users/kderusso/git_tree/kibana/node_modules/require-in-the-middle/index.js:181:27)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/Users/kderusso/git_tree/kibana/src/platform/packages/shared/kbn-es/src/cli_commands/snapshot.ts:15:1)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module.newCompile2 (/Users/kderusso/git_tree/kibana/node_modules/playwright/lib/third_party/pirates.js:46:29)
    at Module._compile (/Users/kderusso/git_tree/kibana/node_modules/pirates/lib/index.js:129:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Object.newLoader (/Users/kderusso/git_tree/kibana/node_modules/pirates/lib/index.js:134:7)
    at Object.newLoader2 [as .ts] (/Users/kderusso/git_tree/kibana/node_modules/playwright/lib/third_party/pirates.js:52:22)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at Module.patchedRequire (/Users/kderusso/git_tree/kibana/node_modules/require-in-the-middle/index.js:256:27)
    at Module.Hook._require.Module.require (/Users/kderusso/git_tree/kibana/node_modules/require-in-the-middle/index.js:181:27)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/Users/kderusso/git_tree/kibana/src/platform/packages/shared/kbn-es/src/cli_commands/index.ts:10:1)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module.newCompile2 (/Users/kderusso/git_tree/kibana/node_modules/playwright/lib/third_party/pirates.js:46:29)
    at Module._compile (/Users/kderusso/git_tree/kibana/node_modules/pirates/lib/index.js:129:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Object.newLoader (/Users/kderusso/git_tree/kibana/node_modules/pirates/lib/index.js:134:7)
    at Object.newLoader2 [as .ts] (/Users/kderusso/git_tree/kibana/node_modules/playwright/lib/third_party/pirates.js:52:22)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at Module.patchedRequire (/Users/kderusso/git_tree/kibana/node_modules/require-in-the-middle/index.js:256:27)
    at Module.Hook._require.Module.require (/Users/kderusso/git_tree/kibana/node_modules/require-in-the-middle/index.js:181:27)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/Users/kderusso/git_tree/kibana/src/platform/packages/shared/kbn-es/src/cli.ts:13:1)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module.newCompile2 (/Users/kderusso/git_tree/kibana/node_modules/playwright/lib/third_party/pirates.js:46:29)
    at Module._compile (/Users/kderusso/git_tree/kibana/node_modules/pirates/lib/index.js:129:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Object.newLoader (/Users/kderusso/git_tree/kibana/node_modules/pirates/lib/index.js:134:7)
    at Object.newLoader2 [as .ts] (/Users/kderusso/git_tree/kibana/node_modules/playwright/lib/third_party/pirates.js:52:22)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at Module.patchedRequire (/Users/kderusso/git_tree/kibana/node_modules/require-in-the-middle/index.js:256:27)
    at Module.Hook._require.Module.require (/Users/kderusso/git_tree/kibana/node_modules/require-in-the-middle/index.js:181:27)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/Users/kderusso/git_tree/kibana/src/platform/packages/shared/kbn-es/index.ts:10:1)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module.newCompile2 (/Users/kderusso/git_tree/kibana/node_modules/playwright/lib/third_party/pirates.js:46:29)
    at Module._compile (/Users/kderusso/git_tree/kibana/node_modules/pirates/lib/index.js:129:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Object.newLoader (/Users/kderusso/git_tree/kibana/node_modules/pirates/lib/index.js:134:7)
    at Object.newLoader2 [as .ts] (/Users/kderusso/git_tree/kibana/node_modules/playwright/lib/third_party/pirates.js:52:22)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at Module.patchedRequire (/Users/kderusso/git_tree/kibana/node_modules/require-in-the-middle/index.js:256:27)
    at Module.Hook._require.Module.require (/Users/kderusso/git_tree/kibana/node_modules/require-in-the-middle/index.js:181:27)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/Users/kderusso/git_tree/kibana/src/platform/packages/shared/kbn-test/src/es/test_es_cluster.ts:18:1)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module.newCompile2 (/Users/kderusso/git_tree/kibana/node_modules/playwright/lib/third_party/pirates.js:46:29)
    at Module._compile (/Users/kderusso/git_tree/kibana/node_modules/pirates/lib/index.js:129:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Object.newLoader (/Users/kderusso/git_tree/kibana/node_modules/pirates/lib/index.js:134:7)
    at Object.newLoader2 [as .ts] (/Users/kderusso/git_tree/kibana/node_modules/playwright/lib/third_party/pirates.js:52:22)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at Module.patchedRequire (/Users/kderusso/git_tree/kibana/node_modules/require-in-the-middle/index.js:256:27)
    at Module.Hook._require.Module.require (/Users/kderusso/git_tree/kibana/node_modules/require-in-the-middle/index.js:181:27)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/Users/kderusso/git_tree/kibana/src/platform/packages/shared/kbn-test/src/es/index.ts:10:1)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module.newCompile2 (/Users/kderusso/git_tree/kibana/node_modules/playwright/lib/third_party/pirates.js:46:29)
    at Module._compile (/Users/kderusso/git_tree/kibana/node_modules/pirates/lib/index.js:129:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Object.newLoader (/Users/kderusso/git_tree/kibana/node_modules/pirates/lib/index.js:134:7)
    at Object.newLoader2 [as .ts] (/Users/kderusso/git_tree/kibana/node_modules/playwright/lib/third_party/pirates.js:52:22)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at Module.patchedRequire (/Users/kderusso/git_tree/kibana/node_modules/require-in-the-middle/index.js:256:27)
    at Module.Hook._require.Module.require (/Users/kderusso/git_tree/kibana/node_modules/require-in-the-middle/index.js:181:27)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/Users/kderusso/git_tree/kibana/src/platform/packages/shared/kbn-test/src/functional_test_runner/functional_test_runner.ts:27:1)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module.newCompile2 (/Users/kderusso/git_tree/kibana/node_modules/playwright/lib/third_party/pirates.js:46:29)
    at Module._compile (/Users/kderusso/git_tree/kibana/node_modules/pirates/lib/index.js:129:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Object.newLoader (/Users/kderusso/git_tree/kibana/node_modules/pirates/lib/index.js:134:7)
    at Object.newLoader2 [as .ts] (/Users/kderusso/git_tree/kibana/node_modules/playwright/lib/third_party/pirates.js:52:22)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at Module.patchedRequire (/Users/kderusso/git_tree/kibana/node_modules/require-in-the-middle/index.js:256:27)
    at Module.Hook._require.Module.require (/Users/kderusso/git_tree/kibana/node_modules/require-in-the-middle/index.js:181:27)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/Users/kderusso/git_tree/kibana/src/platform/packages/shared/kbn-test/src/functional_test_runner/index.ts:10:1)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module.newCompile2 (/Users/kderusso/git_tree/kibana/node_modules/playwright/lib/third_party/pirates.js:46:29)
    at Module._compile (/Users/kderusso/git_tree/kibana/node_modules/pirates/lib/index.js:129:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Object.newLoader (/Users/kderusso/git_tree/kibana/node_modules/pirates/lib/index.js:134:7)
    at Object.newLoader2 [as .ts] (/Users/kderusso/git_tree/kibana/node_modules/playwright/lib/third_party/pirates.js:52:22)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at Module.patchedRequire (/Users/kderusso/git_tree/kibana/node_modules/require-in-the-middle/index.js:256:27)
    at Module.Hook._require.Module.require (/Users/kderusso/git_tree/kibana/node_modules/require-in-the-middle/index.js:181:27)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/Users/kderusso/git_tree/kibana/src/platform/packages/shared/kbn-test/src/functional_tests/start_servers/flags.ts:17:1)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module.newCompile2 (/Users/kderusso/git_tree/kibana/node_modules/playwright/lib/third_party/pirates.js:46:29)
    at Module._compile (/Users/kderusso/git_tree/kibana/node_modules/pirates/lib/index.js:129:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Object.newLoader (/Users/kderusso/git_tree/kibana/node_modules/pirates/lib/index.js:134:7)
    at Object.newLoader2 [as .ts] (/Users/kderusso/git_tree/kibana/node_modules/playwright/lib/third_party/pirates.js:52:22)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at Module.patchedRequire (/Users/kderusso/git_tree/kibana/node_modules/require-in-the-middle/index.js:256:27)
    at Module.Hook._require.Module.require (/Users/kderusso/git_tree/kibana/node_modules/require-in-the-middle/index.js:181:27)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/Users/kderusso/git_tree/kibana/src/platform/packages/shared/kbn-test/src/functional_tests/start_servers/cli.ts:14:1)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module.newCompile2 (/Users/kderusso/git_tree/kibana/node_modules/playwright/lib/third_party/pirates.js:46:29)
    at Module._compile (/Users/kderusso/git_tree/kibana/node_modules/pirates/lib/index.js:129:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)

```