Replace <account> with {account} in i18n strings (#267775)
## Summary

Replaces `<account>` with `{account}` inside the Snowflake connector's
`i18n` message strings as well as placholder URL text.

The presence of angle brackets was causing error messages on Kibana
startup:

```
installHook.js:1 Error: [@formatjs/intl Error FORMAT_ERROR] Error formatting default message for: "core.kibanaConnectorSpecs.snowflake.auth.oauth.authorizationUrl.helpText", rendering default message verbatim
MessageID: core.kibanaConnectorSpecs.snowflake.auth.oauth.authorizationUrl.helpText
Default Message: Snowflake OAuth authorization URL. Replace <account> with your Snowflake account identifier.
Description: undefined

installHook.js:1 Error: [@formatjs/intl Error FORMAT_ERROR] Error formatting default message for: "core.kibanaConnectorSpecs.snowflake.auth.oauth.tokenUrl.helpText", rendering default message verbatim
MessageID: core.kibanaConnectorSpecs.snowflake.auth.oauth.tokenUrl.helpText
Default Message: Snowflake OAuth token endpoint. Replace <account> with your Snowflake account identifier.
Description: undefined
```


### Checklist

Check the PR satisfies following conditions. 

Reviewers should verify this PR satisfies this list as well.

- [x] Any text added follows [EUI's writing
guidelines](https://elastic.github.io/eui/#/guidelines/writing), uses
sentence case text and includes [i18n
support](https://github.com/elastic/kibana/blob/main/src/platform/packages/shared/kbn-i18n/README.md)
- [x]
[Documentation](https://www.elastic.co/guide/en/kibana/master/development-documentation.html)
was added for features that require explanation or tutorials