[Fleet] click Add menu button in ensemble test (#262754)
## Summary

Ensemble nightly Fleet tests were failing for a few days

https://github.com/elastic/ensemble/actions/runs/24325275620/job/71045956943

### Test info
```
- Name: stateful/fleet_ea_enrollment.spec.ts >> Fleet Elastic Agent enrollment flow
- Location: x-pack/solutions/observability/plugins/observability_onboarding/e2e/playwright/stateful/fleet_ea_enrollment.spec.ts:17:5
```

### Error details

Test timeout of 400000ms exceeded.

```
Error: locator.click: Test timeout of 400000ms exceeded.
Call log:
  - waiting for getByTestId('addAgentButton')
```

When running locally, found that the test was stuck before opening the
Add agent flyout.
Adding a missing click to the new Add menu button.

```
npx playwright test -c ./x-pack/solutions/observability/plugins/observability_onboarding/e2e/playwright/playwright.config.ts --reporter list --headed x-pack/solutions/observability/plugins/observability_onboarding/e2e/playwright/stateful/fleet_ea_enrollment.spec.ts
```

<img width="1783" height="1036" alt="image"
src="https://github.com/user-attachments/assets/580092e4-9eb1-4eb4-b808-65b0f678ea48"
/>


### Checklist

Check the PR satisfies following conditions. 

Reviewers should verify this PR satisfies this list as well.

- [ ] Any text added follows [EUI's writing
guidelines](https://elastic.github.io/eui/#/guidelines/writing), uses
sentence case text and includes [i18n
support](https://github.com/elastic/kibana/blob/main/src/platform/packages/shared/kbn-i18n/README.md)
- [ ]
[Documentation](https://www.elastic.co/guide/en/kibana/master/development-documentation.html)
was added for features that require explanation or tutorials
- [ ] [Unit or functional
tests](https://www.elastic.co/guide/en/kibana/master/development-tests.html)
were updated or added to match the most common scenarios
- [ ] If a plugin configuration key changed, check if it needs to be
allowlisted in the cloud and added to the [docker
list](https://github.com/elastic/kibana/blob/main/src/dev/build/tasks/os_packages/docker_generator/resources/base/bin/kibana-docker)
- [ ] This was checked for breaking HTTP API changes, and any breaking
changes have been approved by the breaking-change committee. The
`release_note:breaking` label should be applied in these situations.
- [ ] [Flaky Test
Runner](https://ci-stats.kibana.dev/trigger_flaky_test_runner/1) was
used on any tests changed
- [ ] The PR description includes the appropriate Release Notes section,
and the correct `release_note:*` label is applied per the
[guidelines](https://www.elastic.co/guide/en/kibana/master/contributing.html#kibana-release-notes-process)
- [ ] Review the [backport
guidelines](https://docs.google.com/document/d/1VyN5k91e5OVumlc0Gb9RPa3h1ewuPE705nRtioPiTvY/edit?usp=sharing)
and apply applicable `backport:*` labels.

### Identify risks

Does this PR introduce any risks? For example, consider risks like hard
to test bugs, performance regression, potential of data loss.

Describe the risk, its severity, and mitigation for each identified
risk. Invite stakeholders and evaluate how to proceed before merging.

- [ ] [See some risk
examples](https://github.com/elastic/kibana/blob/main/RISK_MATRIX.mdx)
- [ ] ...